### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by rcalabro** [alpertuna/react-metismenu#19]
Hi,

Is this issue #7 back? 

Running on a universal app,

`[1] ReferenceError: window is not defined
[1]     at /Users/rcalabro/GitLab/Private/coachee-saga/node_modules/react-metismenu/lib/reducers/content.js:74:35
[1]     at /Users/rcalabro/GitLab/Private/coachee-saga/node_modules/react-metismenu/lib/reducers/content.js:80:15
[1]     at content (/Users/rcalabro/GitLab/Private/coachee-saga/node_modules/react-metismenu/lib/reducers/content.js:103:10)
[1]     at combination (/Users/rcalabro/GitLab/Private/coachee-saga/node_modules/redux/lib/combineReducers.js:132:29)
[1]     at Object.dispatch (/Users/rcalabro/GitLab/Private/coachee-saga/node_modules/redux/lib/createStore.js:179:22)
[1]     at MetisMenu.changeActiveLinkFromLocation (/Users/rcalabro/GitLab/Private/coachee-saga/node_modules/react-metismenu/lib/components/MetisMenu.js:134:18)
[1]     at MetisMenu.updateActiveLink (/Users/rcalabro/GitLab/Private/coachee-saga/node_modules/react-metismenu/lib/components/MetisMenu.js:139:274)
[1]     at new MetisMenu (/Users/rcalabro/GitLab/Private/coachee-saga/node_modules/react-metismenu/lib/components/MetisMenu.js:69:13)
[1]     at /Users/rcalabro/GitLab/Private/coachee-saga/node_modules/react-dom/lib/ReactCompositeComponent.js:295:18
[1]     at measureLifeCyclePerf (/Users/rcalabro/GitLab/Private/coachee-saga/node_modules/react-dom/lib/ReactCompositeComponent.js:75:12)`

Thanks!

**Comment by alpertuna** [comment]
Hi @rcalabro,
I check it and the reason is that you probably used `activeLinkFromLocation`. In this case, it uses `window` global variable to get location/url at browser address bar in order to specify active link. When you render it at server, there is no `window` global variable. That's why it crushes.

To prevent this, you should remove `activeLinkFromLocation` and activate link by front side.

**Comment by rcalabro** [comment]
Thanks!  Working perfectly now =)

**Comment by alpertuna** [comment]
You're welcome :blush: It seems a warning message is needed there to warn developers, I will put it soon.
